minimum_pre_commit_version: 2.7.1
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-case-conflict
