sudo: false
language: elixir
elixir:
  - 1.8.2
  - 1.9.4
  - 1.10.4
  - 1.11.3
otp_release:
  - 20.3.8.22
  - 21.3.8.1
  - 22.3.4
  - 23.0.3
git:
  quiet: true
env:
  - PLT_DIR=$HOME/.plt
cache:
  directories:
    - _build
    - deps
    - $PLT_DIR
jobs:
  exclude:
  - elixir: 1.8.2
    otp_release: 23.0.3
  - elixir: 1.9.4
    otp_release: 23.0.3
  - elixir: 1.10.4
    otp_release: 20.3.8.22
before_script:
  - mkdir -p $PLT_DIR
  - mix deps.get --force
  - mix deps.compile --force
  - mix compile --force
  - travis_wait 30 mix dialyzer --plt
  - MIX_ENV=test mix deps.get --force
  - MIX_ENV=test mix deps.compile --force
script:
  - mix credo --strict --all
  - MIX_ENV=test mix compile --force --warnings-as-errors
  - MIX_ENV=test mix format --check-formatted --dry-run
  - mix purge.db
  - MIX_ENV=test mix coveralls.json --no-start
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mix inch.report
notifications:
  email:
    - randy@heroictek.com
